# Generated by Django 5.1.2 on 2024-11-08 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('language', models.CharField(max_length=1000)),
                ('image', models.ImageField(upload_to='Project_images')),
            ],
        ),
    ]
